using BuildSmart.Core.Domain.Common;

namespace BuildSmart.Core.Domain.Entities;

public class TaskComment : BaseEntity
{
    public Guid JobTaskId { get; set; }
    public JobTask JobTask { get; set; } = null!;

    public Guid AuthorId { get; set; }
    public User Author { get; set; } = null!;

    public string Content { get; set; } = string.Empty;

    /// <summary>
    /// Indicates if this comment was automatically generated by system actions (e.g. task rejection reasons).
    /// </summary>
    public bool IsSystemNote { get; set; } = false;

    /// <summary>
    /// Attachments / photos uploaded with the comment.
    /// </summary>
    public List<string> ImageUrls { get; set; } = new();
}
