-- DIRECT UPDATE SCRIPT FOR LIVE DATABASE

UPDATE "ServiceSkus" SET "BasePrice" = 4.09, "CalculationFormula" = '', "Description" = 'Шпакловане и фугиране на гипсокартон', "UnitType" = 'sqm' WHERE "SkuCode" = 'DRYW-006';
UPDATE "ServiceSkus" SET "BasePrice" = 15.34, "CalculationFormula" = '1', "Description" = 'Запечатване на мокри помещения.', "UnitType" = 'sqm' WHERE "SkuCode" = 'TILE-PREP-HYDRO';
UPDATE "ServiceSkus" SET "BasePrice" = 15.34, "CalculationFormula" = '1', "Description" = 'LAN/TV/СОТ.', "UnitType" = 'pcs' WHERE "SkuCode" = 'ELEC-POINT-LV';
UPDATE "ServiceSkus" SET "BasePrice" = 3.32, "CalculationFormula" = '', "Description" = 'Market range: €5 - €8', "UnitType" = '€/кв.м' WHERE "SkuCode" = 'PANT-003';
UPDATE "ServiceSkus" SET "BasePrice" = 122.71, "CalculationFormula" = '1', "Description" = 'Подмяна на основните метални тръби.', "UnitType" = 'pcs' WHERE "SkuCode" = 'PLMB-RISER-REPLACE';
UPDATE "ServiceSkus" SET "BasePrice" = 40.90, "CalculationFormula" = '1', "Description" = 'Уреди.', "UnitType" = 'pcs' WHERE "SkuCode" = 'PLMB-APPLIANCE';
UPDATE "ServiceSkus" SET "BasePrice" = 30.68, "CalculationFormula" = '1', "Description" = 'Нов водомер.', "UnitType" = 'pcs' WHERE "SkuCode" = 'PLMB-METER-REPLACE';
UPDATE "ServiceSkus" SET "BasePrice" = 383.47, "CalculationFormula" = '1', "Description" = 'Къртене на баня.', "UnitType" = 'pcs' WHERE "SkuCode" = 'DEMO-BATH-FULL';
UPDATE "ServiceSkus" SET "BasePrice" = 25.56, "CalculationFormula" = '1', "Description" = 'Къртене на бетон.', "UnitType" = 'sqm' WHERE "SkuCode" = 'DEMO-WALL-CONC';
UPDATE "ServiceSkus" SET "BasePrice" = 3.66, "CalculationFormula" = '', "Description" = 'Market range: €6.81 - €7.5', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-110';
UPDATE "ServiceSkus" SET "BasePrice" = 20.45, "CalculationFormula" = '1', "Description" = 'Монтаж на предстенна обшивка.', "UnitType" = 'sqm' WHERE "SkuCode" = 'DRYW-WALL-LINING';
UPDATE "ServiceSkus" SET "BasePrice" = 34.12, "CalculationFormula" = '', "Description" = 'Market range: €63.56 - €69.93', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-097';
UPDATE "ServiceSkus" SET "BasePrice" = 3.32, "CalculationFormula" = '', "Description" = 'Market range: €6 - €7', "UnitType" = '€/бр' WHERE "SkuCode" = 'ELEC-029';
UPDATE "ServiceSkus" SET "BasePrice" = 15.34, "CalculationFormula" = '', "Description" = 'Труд за оформяне на конзолна кутия, заголване и подготовка на кабелите за 1 брой контакт, ключ или лампа.', "UnitType" = 'Per Quantity (Item)' WHERE "SkuCode" = 'ELEC-008';
UPDATE "ServiceSkus" SET "BasePrice" = 35.79, "CalculationFormula" = '1', "Description" = 'Душ батерия.', "UnitType" = 'pcs' WHERE "SkuCode" = 'PLMB-SHOWER-FIXTURE';
UPDATE "ServiceSkus" SET "BasePrice" = 19.53, "CalculationFormula" = '', "Description" = 'Market range: €36.38 - €40.03', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-035';
UPDATE "ServiceSkus" SET "BasePrice" = 4.35, "CalculationFormula" = '1', "Description" = 'Боядисване с цветен латекс.', "UnitType" = 'sqm' WHERE "SkuCode" = 'PANT-PAINT-COLOR';
UPDATE "ServiceSkus" SET "BasePrice" = 6.14, "CalculationFormula" = '1', "Description" = 'Полагане на ламиниран паркет.', "UnitType" = 'sqm' WHERE "SkuCode" = 'TILE-LAMINATE';
UPDATE "ServiceSkus" SET "BasePrice" = 21.87, "CalculationFormula" = '', "Description" = 'Market range: €40.73 - €44.82', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-048';
UPDATE "ServiceSkus" SET "BasePrice" = 3.58, "CalculationFormula" = '', "Description" = 'Market range: €6 - €8', "UnitType" = '€/кв.м' WHERE "SkuCode" = 'PANT-002';
UPDATE "ServiceSkus" SET "BasePrice" = 4.38, "CalculationFormula" = '', "Description" = 'Market range: €8.16 - €8.98', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-117';
UPDATE "ServiceSkus" SET "BasePrice" = 7.28, "CalculationFormula" = '', "Description" = 'Market range: €13.55 - €14.92', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-073';
UPDATE "ServiceSkus" SET "BasePrice" = 71.58, "CalculationFormula" = '1', "Description" = 'Бойлер до 100л.', "UnitType" = 'pcs' WHERE "SkuCode" = 'PLMB-BOILER';
UPDATE "ServiceSkus" SET "BasePrice" = 7.67, "CalculationFormula" = '1', "Description" = 'Премахване на настилки.', "UnitType" = 'sqm' WHERE "SkuCode" = 'DEMO-FLOOR-TILE';
UPDATE "ServiceSkus" SET "BasePrice" = 10.23, "CalculationFormula" = '1', "Description" = 'Събаряне на тухлени стени.', "UnitType" = 'sqm' WHERE "SkuCode" = 'DEMO-WALL-BRICK';
UPDATE "ServiceSkus" SET "BasePrice" = 10.22, "CalculationFormula" = '', "Description" = 'Market range: €19.02 - €20.93', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-053';
UPDATE "ServiceSkus" SET "BasePrice" = 11.66, "CalculationFormula" = '', "Description" = 'Market range: €21.71 - €23.9', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-054';
UPDATE "ServiceSkus" SET "BasePrice" = 127.82, "CalculationFormula" = '1', "Description" = 'Наемане на строителен контейнер.', "UnitType" = 'pcs' WHERE "SkuCode" = 'DEMO-DISPOSAL';
UPDATE "ServiceSkus" SET "BasePrice" = 1.02, "CalculationFormula" = 'if(Contains(elec_scope, ''Цялостна''), global_total_sqm * 3.5, if(Contains(elec_scope, ''Частичен''), global_total_sqm * 1.0, 0))', "Description" = 'Издърпване и фиксиране на кабел.', "UnitType" = 'm' WHERE "SkuCode" = 'ELEC-CABLE-LAY';
UPDATE "ServiceSkus" SET "BasePrice" = 1.45, "CalculationFormula" = '', "Description" = 'Market range: €2.69 - €2.97', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-115';
UPDATE "ServiceSkus" SET "BasePrice" = 4.38, "CalculationFormula" = '', "Description" = 'Market range: €8.16 - €8.98', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-067';
UPDATE "ServiceSkus" SET "BasePrice" = 2.40, "CalculationFormula" = '', "Description" = 'Market range: €4.4 - €5', "UnitType" = '€/лин.м' WHERE "SkuCode" = 'ELEC-016';
UPDATE "ServiceSkus" SET "BasePrice" = 20.45, "CalculationFormula" = '', "Description" = 'Декоративна облицовка.', "UnitType" = 'sqm' WHERE "SkuCode" = 'TILE-008';
UPDATE "ServiceSkus" SET "BasePrice" = 29.45, "CalculationFormula" = '', "Description" = 'Market range: €54.85 - €60.34', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-098';
UPDATE "ServiceSkus" SET "BasePrice" = 7.67, "CalculationFormula" = 'if(Contains(elec_walls, ''Бетон'') && Contains(elec_scope, ''Цялостна''), global_total_sqm * 3.5, 0)', "Description" = 'Изкопаване на канал в бетон.', "UnitType" = 'm' WHERE "SkuCode" = 'ELEC-CHASE-CONC';
UPDATE "ServiceSkus" SET "BasePrice" = 17.90, "CalculationFormula" = '', "Description" = 'Изграждане на захранваща точка за специфични моторизирани уреди (вентилатор в баня, външни ролетни щори).', "UnitType" = 'Per Quantity (Item)' WHERE "SkuCode" = 'ELEC-010';
UPDATE "ServiceSkus" SET "BasePrice" = 4.38, "CalculationFormula" = '', "Description" = 'Market range: €8.16 - €8.98', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-064';
UPDATE "ServiceSkus" SET "BasePrice" = 26.25, "CalculationFormula" = '', "Description" = 'Market range: €48.89 - €53.79', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-096';
UPDATE "ServiceSkus" SET "BasePrice" = 2.93, "CalculationFormula" = '', "Description" = 'Market range: €5.46 - €6.01', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-087';
UPDATE "ServiceSkus" SET "BasePrice" = 37.35, "CalculationFormula" = '', "Description" = 'Market range: €69.57 - €76.54', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-099';
UPDATE "ServiceSkus" SET "BasePrice" = 4.21, "CalculationFormula" = '', "Description" = 'Market range: €7.85 - €8.64', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-037';
UPDATE "ServiceSkus" SET "BasePrice" = 3.32, "CalculationFormula" = '1', "Description" = 'Боядисване с бял латекс.', "UnitType" = 'sqm' WHERE "SkuCode" = 'PANT-PAINT-WHITE';
UPDATE "ServiceSkus" SET "BasePrice" = 12.25, "CalculationFormula" = '', "Description" = 'Market range: €22.82 - €25.11', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-041';
UPDATE "ServiceSkus" SET "BasePrice" = 9.20, "CalculationFormula" = '', "Description" = '', "UnitType" = 'Per sqm' WHERE "SkuCode" = 'TILE-006';
UPDATE "ServiceSkus" SET "BasePrice" = 4.51, "CalculationFormula" = '', "Description" = 'Market range: €8.4 - €9.25', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-085';
UPDATE "ServiceSkus" SET "BasePrice" = 2.17, "CalculationFormula" = '', "Description" = 'Market range: €4.04 - €4.46', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-066';
UPDATE "ServiceSkus" SET "BasePrice" = 45.36, "CalculationFormula" = '', "Description" = 'Market range: €84.48 - €92.94', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-141';
UPDATE "ServiceSkus" SET "BasePrice" = 1.45, "CalculationFormula" = '', "Description" = 'Market range: €2.69 - €2.97', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-061';
UPDATE "ServiceSkus" SET "BasePrice" = 4.38, "CalculationFormula" = '', "Description" = 'Market range: €8.16 - €8.98', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-121';
UPDATE "ServiceSkus" SET "BasePrice" = 17.49, "CalculationFormula" = '', "Description" = 'Market range: €32.57 - €35.84', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-055';
UPDATE "ServiceSkus" SET "BasePrice" = 12.78, "CalculationFormula" = '', "Description" = '', "UnitType" = 'Per Item' WHERE "SkuCode" = 'PANT-005';
UPDATE "ServiceSkus" SET "BasePrice" = 2.93, "CalculationFormula" = '', "Description" = 'Market range: €5.46 - €6.01', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-031';
UPDATE "ServiceSkus" SET "BasePrice" = 5.83, "CalculationFormula" = '', "Description" = 'Market range: €10.85 - €11.95', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-130';
UPDATE "ServiceSkus" SET "BasePrice" = 3.66, "CalculationFormula" = '', "Description" = 'Market range: €6.81 - €7.5', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-068';
UPDATE "ServiceSkus" SET "BasePrice" = 2.47, "CalculationFormula" = '', "Description" = 'Market range: €4.6 - €5.07', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-107';
UPDATE "ServiceSkus" SET "BasePrice" = 26.25, "CalculationFormula" = '', "Description" = 'Market range: €48.89 - €53.79', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-092';
UPDATE "ServiceSkus" SET "BasePrice" = 8.76, "CalculationFormula" = '', "Description" = 'Market range: €16.32 - €17.96', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-039';
UPDATE "ServiceSkus" SET "BasePrice" = 7.67, "CalculationFormula" = '', "Description" = 'Къртене на канал за тръби.', "UnitType" = 'm' WHERE "SkuCode" = 'PLMB-007';
UPDATE "ServiceSkus" SET "BasePrice" = 13.14, "CalculationFormula" = '', "Description" = 'Market range: €24.48 - €26.93', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-042';
UPDATE "ServiceSkus" SET "BasePrice" = 65.65, "CalculationFormula" = '', "Description" = 'Market range: €122.28 - €134.51', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-123';
UPDATE "ServiceSkus" SET "BasePrice" = 33.23, "CalculationFormula" = '', "Description" = 'Market range: €60 - €70', "UnitType" = '€/куб.м' WHERE "SkuCode" = 'DEMO-002';
UPDATE "ServiceSkus" SET "BasePrice" = 11.94, "CalculationFormula" = '', "Description" = 'Market range: €21.7 - €25', "UnitType" = '€/бр' WHERE "SkuCode" = 'ELEC-025';
UPDATE "ServiceSkus" SET "BasePrice" = 8.76, "CalculationFormula" = '', "Description" = 'Market range: €16.32 - €17.96', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-119';
UPDATE "ServiceSkus" SET "BasePrice" = 3.07, "CalculationFormula" = '', "Description" = 'Market range: €5.5 - €6.5', "UnitType" = '€/бр' WHERE "SkuCode" = 'ELEC-022';
UPDATE "ServiceSkus" SET "BasePrice" = 5.11, "CalculationFormula" = '', "Description" = 'Market range: €4.9 - €5.4', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-113';
UPDATE "ServiceSkus" SET "BasePrice" = 3.06, "CalculationFormula" = '', "Description" = 'Market range: €5.7 - €6.28', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-126';
UPDATE "ServiceSkus" SET "BasePrice" = 3.20, "CalculationFormula" = '', "Description" = 'Market range: €5.95 - €6.55', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-084';
UPDATE "ServiceSkus" SET "BasePrice" = 6.14, "CalculationFormula" = '', "Description" = 'Премахване на подова замазка.', "UnitType" = 'sqm' WHERE "SkuCode" = 'DEMO-005';
UPDATE "ServiceSkus" SET "BasePrice" = 2.05, "CalculationFormula" = '', "Description" = 'Market range: €3.8 - €4.19', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-106';
UPDATE "ServiceSkus" SET "BasePrice" = 17.90, "CalculationFormula" = '', "Description" = 'Специфично подвързване на ДТЗ за влажни зони и токови кръгове.', "UnitType" = 'pcs' WHERE "SkuCode" = 'ELEC-RCD-INSTALL';
UPDATE "ServiceSkus" SET "BasePrice" = 15.34, "CalculationFormula" = 'if(Contains(elec_lighting, ''LED''), 1, 0)', "Description" = 'Монтаж и подвързване на трансформатор за скрито LED осветление.', "UnitType" = 'pcs' WHERE "SkuCode" = 'ELEC-LED-TRAFO';
UPDATE "ServiceSkus" SET "BasePrice" = 5.11, "CalculationFormula" = '1', "Description" = 'Поставяне на минерална или каменна вата.', "UnitType" = 'sqm' WHERE "SkuCode" = 'DRYW-INSULATION';
UPDATE "ServiceSkus" SET "BasePrice" = 2.47, "CalculationFormula" = '', "Description" = 'Market range: €4.6 - €5.07', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-049';
UPDATE "ServiceSkus" SET "BasePrice" = 3.79, "CalculationFormula" = '', "Description" = 'Market range: €7.05 - €7.77', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-051';
UPDATE "ServiceSkus" SET "BasePrice" = 2.05, "CalculationFormula" = 'if(Contains(elec_scope, ''Цялостна''), global_total_sqm * 3.5, 0)', "Description" = 'Полагане на гофрирана тръба.', "UnitType" = 'm' WHERE "SkuCode" = 'ELEC-LAY-TUBE';
UPDATE "ServiceSkus" SET "BasePrice" = 3.66, "CalculationFormula" = '', "Description" = 'Market range: €6.81 - €7.5', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-102';
UPDATE "ServiceSkus" SET "BasePrice" = 92.03, "CalculationFormula" = '1', "Description" = 'Микроцимент за баня.', "UnitType" = 'sqm' WHERE "SkuCode" = 'MICRO-BATH';
UPDATE "ServiceSkus" SET "BasePrice" = 38.35, "CalculationFormula" = '', "Description" = 'Market range: €70 - €80', "UnitType" = '€/бр' WHERE "SkuCode" = 'PLMB-004';
UPDATE "ServiceSkus" SET "BasePrice" = 3.95, "CalculationFormula" = '', "Description" = 'Market range: €7.36 - €8.1', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-088';
UPDATE "ServiceSkus" SET "BasePrice" = 17.90, "CalculationFormula" = '', "Description" = 'Специфично подвързване на ДТЗ за влажни зони и токови кръгове.', "UnitType" = 'Per Quantity (Item)' WHERE "SkuCode" = 'ELEC-014';
UPDATE "ServiceSkus" SET "BasePrice" = 23.01, "CalculationFormula" = '', "Description" = '', "UnitType" = 'Per linear meter' WHERE "SkuCode" = 'DRYW-004';
UPDATE "ServiceSkus" SET "BasePrice" = 4.40, "CalculationFormula" = '', "Description" = 'Market range: €8.2 - €9', "UnitType" = '€/лин.м' WHERE "SkuCode" = 'ELEC-017';
UPDATE "ServiceSkus" SET "BasePrice" = 2.05, "CalculationFormula" = '', "Description" = 'Market range: €3.8 - €4.19', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-079';
UPDATE "ServiceSkus" SET "BasePrice" = 8.60, "CalculationFormula" = '', "Description" = 'Market range: €16.01 - €17.62', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-127';
UPDATE "ServiceSkus" SET "BasePrice" = 3.20, "CalculationFormula" = '', "Description" = 'Market range: €5.95 - €6.55', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-036';
UPDATE "ServiceSkus" SET "BasePrice" = 6.14, "CalculationFormula" = '', "Description" = 'Изграждане на метална конструкция', "UnitType" = 'sqm' WHERE "SkuCode" = 'DRYW-005';
UPDATE "ServiceSkus" SET "BasePrice" = 15.13, "CalculationFormula" = '', "Description" = 'Market range: €27.2 - €32', "UnitType" = '€/бр' WHERE "SkuCode" = 'ELEC-027';
UPDATE "ServiceSkus" SET "BasePrice" = 7.67, "CalculationFormula" = '', "Description" = 'Market range: €10 - €20', "UnitType" = '€/кв.м' WHERE "SkuCode" = 'DEMO-001';
UPDATE "ServiceSkus" SET "BasePrice" = 2.30, "CalculationFormula" = '1', "Description" = 'Сваляне на стари тапети.', "UnitType" = 'sqm' WHERE "SkuCode" = 'PANT-WALLPAPER-REMOVE';
UPDATE "ServiceSkus" SET "BasePrice" = 102.26, "CalculationFormula" = '', "Description" = 'Монтаж на конзолна тоалетна.', "UnitType" = 'pcs' WHERE "SkuCode" = 'PLMB-006';
UPDATE "ServiceSkus" SET "BasePrice" = 1.87, "CalculationFormula" = '', "Description" = 'Market range: €3.3 - €4', "UnitType" = '€/бр' WHERE "SkuCode" = 'ELEC-018';
UPDATE "ServiceSkus" SET "BasePrice" = 5.83, "CalculationFormula" = '', "Description" = 'Market range: €10.85 - €11.95', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-118';
UPDATE "ServiceSkus" SET "BasePrice" = 30.68, "CalculationFormula" = '1', "Description" = 'Полагане на фаянс или теракот.', "UnitType" = 'sqm' WHERE "SkuCode" = 'TILE-STD';
UPDATE "ServiceSkus" SET "BasePrice" = 7.67, "CalculationFormula" = '', "Description" = '', "UnitType" = 'Per sqm' WHERE "SkuCode" = 'PANT-006';
UPDATE "ServiceSkus" SET "BasePrice" = 148.27, "CalculationFormula" = '', "Description" = 'Market range: €280 - €300', "UnitType" = '€/обект' WHERE "SkuCode" = 'PLMB-001';
UPDATE "ServiceSkus" SET "BasePrice" = 7.67, "CalculationFormula" = '', "Description" = '', "UnitType" = 'Per sqm' WHERE "SkuCode" = 'TILE-007';
UPDATE "ServiceSkus" SET "BasePrice" = 3.07, "CalculationFormula" = '1', "Description" = 'Алуминиеви или PVC ъгли.', "UnitType" = 'm' WHERE "SkuCode" = 'PANT-TAPE-CORNER';
UPDATE "ServiceSkus" SET "BasePrice" = 5.11, "CalculationFormula" = '', "Description" = 'Market range: €9.51 - €10.47', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-103';
UPDATE "ServiceSkus" SET "BasePrice" = 1.75, "CalculationFormula" = '', "Description" = 'Market range: €3.25 - €3.58', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-086';
UPDATE "ServiceSkus" SET "BasePrice" = 20.45, "CalculationFormula" = '1', "Description" = 'Вентилатори или щори.', "UnitType" = 'pcs' WHERE "SkuCode" = 'ELEC-POINT-SPEC';
UPDATE "ServiceSkus" SET "BasePrice" = 2.17, "CalculationFormula" = '', "Description" = 'Market range: €4.04 - €4.46', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-116';
UPDATE "ServiceSkus" SET "BasePrice" = 12.78, "CalculationFormula" = '', "Description" = '', "UnitType" = 'Per Item' WHERE "SkuCode" = 'ELEC-001';
UPDATE "ServiceSkus" SET "BasePrice" = 29.18, "CalculationFormula" = '', "Description" = 'Market range: €54.36 - €59.8', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-133';
UPDATE "ServiceSkus" SET "BasePrice" = 48.12, "CalculationFormula" = '', "Description" = 'Market range: €89.63 - €98.61', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-142';
UPDATE "ServiceSkus" SET "BasePrice" = 1.02, "CalculationFormula" = '', "Description" = 'Market range: €1.9 - €2.1', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-136';
UPDATE "ServiceSkus" SET "BasePrice" = 43.74, "CalculationFormula" = '', "Description" = 'Market range: €81.47 - €89.63', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-134';
UPDATE "ServiceSkus" SET "BasePrice" = 3.62, "CalculationFormula" = '', "Description" = 'Market range: €6.74 - €7.43', "UnitType" = '�/9.70 ����' WHERE "SkuCode" = 'ELEC-139';
UPDATE "ServiceSkus" SET "BasePrice" = 15.34, "CalculationFormula" = '1', "Description" = 'Ежедневно почистване', "UnitType" = 'flat' WHERE "SkuCode" = 'GEN-003';
UPDATE "ServiceSkus" SET "BasePrice" = 36.47, "CalculationFormula" = '', "Description" = 'Market range: €67.92 - €74.72', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-046';
UPDATE "ServiceSkus" SET "BasePrice" = 4.21, "CalculationFormula" = '', "Description" = 'Market range: €7.85 - €8.64', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-108';
UPDATE "ServiceSkus" SET "BasePrice" = 2.47, "CalculationFormula" = '', "Description" = 'Market range: €4.6 - €5.07', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-072';
UPDATE "ServiceSkus" SET "BasePrice" = 60.97, "CalculationFormula" = '', "Description" = 'Market range: €113.56 - €124.93', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-101';
UPDATE "ServiceSkus" SET "BasePrice" = 3.36, "CalculationFormula" = '', "Description" = 'Market range: €6.25 - €6.89', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-050';
UPDATE "ServiceSkus" SET "BasePrice" = 71.58, "CalculationFormula" = '1', "Description" = 'Полагане на микроцимент.', "UnitType" = 'sqm' WHERE "SkuCode" = 'MICRO-STD';
UPDATE "ServiceSkus" SET "BasePrice" = 6.55, "CalculationFormula" = '', "Description" = 'Market range: €12.2 - €13.44', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-034';
UPDATE "ServiceSkus" SET "BasePrice" = 11.25, "CalculationFormula" = '1', "Description" = 'Изравняване на пода.', "UnitType" = 'sqm' WHERE "SkuCode" = 'TILE-PREP-LEVEL';
UPDATE "ServiceSkus" SET "BasePrice" = 18.05, "CalculationFormula" = '', "Description" = 'Market range: €32.6 - €38', "UnitType" = '€/бр' WHERE "SkuCode" = 'ELEC-026';
UPDATE "ServiceSkus" SET "BasePrice" = 2.34, "CalculationFormula" = '', "Description" = 'Market range: €4.35 - €4.8', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-125';
UPDATE "ServiceSkus" SET "BasePrice" = 26.68, "CalculationFormula" = '', "Description" = 'Market range: €49.69 - €54.67', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-058';
UPDATE "ServiceSkus" SET "BasePrice" = 1.16, "CalculationFormula" = '', "Description" = 'Market range: €2.14 - €2.37', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-078';
UPDATE "ServiceSkus" SET "BasePrice" = 43.46, "CalculationFormula" = '', "Description" = '', "UnitType" = 'Per sqm' WHERE "SkuCode" = 'MICO-002';
UPDATE "ServiceSkus" SET "BasePrice" = 4.40, "CalculationFormula" = '', "Description" = 'Market range: €8.2 - €9', "UnitType" = '€/бр' WHERE "SkuCode" = 'ELEC-019';
UPDATE "ServiceSkus" SET "BasePrice" = 23.01, "CalculationFormula" = '1', "Description" = 'Боядисване на декоративни елементи.', "UnitType" = 'pcs' WHERE "SkuCode" = 'PANT-TRIM';
UPDATE "ServiceSkus" SET "BasePrice" = 20.45, "CalculationFormula" = '1', "Description" = 'Обличане на тръби.', "UnitType" = 'm' WHERE "SkuCode" = 'DRYW-BOX';
UPDATE "ServiceSkus" SET "BasePrice" = 2.56, "CalculationFormula" = '(Count(elec_heavy_appliances) + elec_ac_count) * 10', "Description" = 'Дебел кабел за проточни бойлери.', "UnitType" = 'm' WHERE "SkuCode" = 'ELEC-CABLE-HEAVY';
UPDATE "ServiceSkus" SET "BasePrice" = 10.23, "CalculationFormula" = '1', "Description" = 'Шитрок за идеално гладка повърхност.', "UnitType" = 'sqm' WHERE "SkuCode" = 'PANT-SPACKLE-Q5';
UPDATE "ServiceSkus" SET "BasePrice" = 31.23, "CalculationFormula" = '', "Description" = 'Market range: €58.16 - €63.99', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-044';
UPDATE "ServiceSkus" SET "BasePrice" = 72.93, "CalculationFormula" = '', "Description" = 'Market range: €135.84 - €149.43', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-124';
UPDATE "ServiceSkus" SET "BasePrice" = 12.78, "CalculationFormula" = '', "Description" = 'Полагане на FTP/Коаксиален кабел и подготовка на конзола за интернет, телевизия или охранителна техника.', "UnitType" = 'Per Quantity (Item)' WHERE "SkuCode" = 'ELEC-011';
UPDATE "ServiceSkus" SET "BasePrice" = 1.16, "CalculationFormula" = '', "Description" = 'Market range: €2.14 - €2.37', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-069';
UPDATE "ServiceSkus" SET "BasePrice" = 1.75, "CalculationFormula" = '', "Description" = 'Market range: €3.25 - €3.58', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-135';
UPDATE "ServiceSkus" SET "BasePrice" = 140.61, "CalculationFormula" = '', "Description" = 'Market range: €250 - €300', "UnitType" = '€/обект' WHERE "SkuCode" = 'PLMB-002';
UPDATE "ServiceSkus" SET "BasePrice" = 71.58, "CalculationFormula" = '1', "Description" = 'Монтаж на тоалетна.', "UnitType" = 'pcs' WHERE "SkuCode" = 'PLMB-WC-STD';
UPDATE "ServiceSkus" SET "BasePrice" = 1.53, "CalculationFormula" = '', "Description" = 'Издърпване на дебел кабел за проточни бойлери или трифазни консуматори.', "UnitType" = 'Per Linear Meter' WHERE "SkuCode" = 'ELEC-007';
UPDATE "ServiceSkus" SET "BasePrice" = 6.14, "CalculationFormula" = '', "Description" = 'Подреждане на предпазители, ДТЗ и гребени. Цената е за 1 модул (1 предпазител = 1 модул).', "UnitType" = 'Per Quantity (Item)' WHERE "SkuCode" = 'ELEC-013';
UPDATE "ServiceSkus" SET "BasePrice" = 4.38, "CalculationFormula" = '', "Description" = 'Market range: €3.25 - €3.58', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-112';
UPDATE "ServiceSkus" SET "BasePrice" = 1.16, "CalculationFormula" = '', "Description" = 'Market range: €2.14 - €2.37', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-075';
UPDATE "ServiceSkus" SET "BasePrice" = 1.45, "CalculationFormula" = '', "Description" = 'Market range: €2.69 - €2.97', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-070';
UPDATE "ServiceSkus" SET "BasePrice" = 33.23, "CalculationFormula" = '1', "Description" = 'Изграждане на преградна стена.', "UnitType" = 'sqm' WHERE "SkuCode" = 'DRYW-WALL-PARTITION';
UPDATE "ServiceSkus" SET "BasePrice" = 2.34, "CalculationFormula" = '', "Description" = 'Market range: €4.35 - €4.8', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-080';
UPDATE "ServiceSkus" SET "BasePrice" = 21.87, "CalculationFormula" = '', "Description" = 'Market range: €40.73 - €44.82', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-045';
UPDATE "ServiceSkus" SET "BasePrice" = 3.07, "CalculationFormula" = '', "Description" = 'Изкопаване на канал за полагане на кабели в тухлена зидария.', "UnitType" = 'Per Linear Meter' WHERE "SkuCode" = 'ELEC-004';
UPDATE "ServiceSkus" SET "BasePrice" = 7.16, "CalculationFormula" = '', "Description" = 'Market range: €10 - €18', "UnitType" = '€/лин.м' WHERE "SkuCode" = 'DRYW-003';
UPDATE "ServiceSkus" SET "BasePrice" = 3.58, "CalculationFormula" = '', "Description" = 'Market range: €6 - €8', "UnitType" = '€/лин.м' WHERE "SkuCode" = 'TILE-002';
UPDATE "ServiceSkus" SET "BasePrice" = 10.22, "CalculationFormula" = '', "Description" = 'Market range: €19.02 - €20.93', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-040';
UPDATE "ServiceSkus" SET "BasePrice" = 11.66, "CalculationFormula" = '', "Description" = 'Market range: €21.71 - €23.9', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-144';
UPDATE "ServiceSkus" SET "BasePrice" = 4.21, "CalculationFormula" = '', "Description" = 'Market range: €7.85 - €8.64', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-032';
UPDATE "ServiceSkus" SET "BasePrice" = 61.36, "CalculationFormula" = '', "Description" = '', "UnitType" = 'Per Item' WHERE "SkuCode" = 'PLMB-005';
UPDATE "ServiceSkus" SET "BasePrice" = 0.77, "CalculationFormula" = '', "Description" = 'Market range: €1 - €2', "UnitType" = '€/кв.м' WHERE "SkuCode" = 'PANT-004';
UPDATE "ServiceSkus" SET "BasePrice" = 4.09, "CalculationFormula" = 'if(Contains(elec_walls, ''Тухла'') && Contains(elec_scope, ''Цялостна''), global_total_sqm * 3.5, 0)', "Description" = 'Изкопаване на канал за полагане на кабели в тухлена зидария.', "UnitType" = 'm' WHERE "SkuCode" = 'ELEC-CHASE-BRICK';
UPDATE "ServiceSkus" SET "BasePrice" = 43.74, "CalculationFormula" = '', "Description" = 'Market range: €81.47 - €89.63', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-128';
UPDATE "ServiceSkus" SET "BasePrice" = 35.74, "CalculationFormula" = '', "Description" = 'Market range: €66.57 - €73.23', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-057';
UPDATE "ServiceSkus" SET "BasePrice" = 2.05, "CalculationFormula" = '', "Description" = '', "UnitType" = 'Per sqm' WHERE "SkuCode" = 'DEMO-004';
UPDATE "ServiceSkus" SET "BasePrice" = 2.47, "CalculationFormula" = '', "Description" = 'Market range: €4.6 - €5.07', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-105';
UPDATE "ServiceSkus" SET "BasePrice" = 23.01, "CalculationFormula" = '', "Description" = 'Специфично опроводяване за управление на едно осветление от 2 или повече места.', "UnitType" = 'Per Quantity (Item)' WHERE "SkuCode" = 'ELEC-009';
UPDATE "ServiceSkus" SET "BasePrice" = 5.88, "CalculationFormula" = '', "Description" = 'Market range: €9 - €14', "UnitType" = '€/кв.м' WHERE "SkuCode" = 'TILE-004';
UPDATE "ServiceSkus" SET "BasePrice" = 8.60, "CalculationFormula" = '', "Description" = 'Market range: €16.01 - €17.62', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-122';
UPDATE "ServiceSkus" SET "BasePrice" = 29.75, "CalculationFormula" = '', "Description" = 'Market range: €55.4 - €60.95', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-120';
UPDATE "ServiceSkus" SET "BasePrice" = 51.06, "CalculationFormula" = '', "Description" = 'Market range: €95.1 - €104.62', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-129';
UPDATE "ServiceSkus" SET "BasePrice" = 2.93, "CalculationFormula" = '', "Description" = 'Market range: €5.46 - €6.01', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-063';
UPDATE "ServiceSkus" SET "BasePrice" = 30.64, "CalculationFormula" = '', "Description" = 'Market range: €57.06 - €62.77', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-059';
UPDATE "ServiceSkus" SET "BasePrice" = 26.25, "CalculationFormula" = '', "Description" = 'Market range: €48.89 - €53.79', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-132';
UPDATE "ServiceSkus" SET "BasePrice" = 14.59, "CalculationFormula" = '', "Description" = 'Market range: €27.18 - €29.9', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-038';
UPDATE "ServiceSkus" SET "BasePrice" = 0.77, "CalculationFormula" = '', "Description" = 'Market range: €1 - €2', "UnitType" = '€/кв.м' WHERE "SkuCode" = 'PANT-001';
UPDATE "ServiceSkus" SET "BasePrice" = 10.23, "CalculationFormula" = '', "Description" = '', "UnitType" = 'Per sqm' WHERE "SkuCode" = 'MICO-003';
UPDATE "ServiceSkus" SET "BasePrice" = 35.79, "CalculationFormula" = '1', "Description" = 'Тръби за топла, студена вода и канал.', "UnitType" = 'pcs' WHERE "SkuCode" = 'PLMB-POINT-NEW';
UPDATE "ServiceSkus" SET "BasePrice" = 1.02, "CalculationFormula" = '1', "Description" = 'Окончателно почистване на обекта', "UnitType" = 'sqm' WHERE "SkuCode" = 'GEN-002';
UPDATE "ServiceSkus" SET "BasePrice" = 6.14, "CalculationFormula" = '', "Description" = 'Нивелиране на под.', "UnitType" = 'sqm' WHERE "SkuCode" = 'TILE-009';
UPDATE "ServiceSkus" SET "BasePrice" = 11.76, "CalculationFormula" = '', "Description" = 'Market range: €18 - €28', "UnitType" = '€/кв.м' WHERE "SkuCode" = 'DRYW-001';
UPDATE "ServiceSkus" SET "BasePrice" = 0.77, "CalculationFormula" = '', "Description" = 'Издърпване и фиксиране на кабел СВТ/ПВВ-МБ1 (напр. 3х1.5, 3х2.5, 3х4).', "UnitType" = 'Per Linear Meter' WHERE "SkuCode" = 'ELEC-006';
UPDATE "ServiceSkus" SET "BasePrice" = 1.02, "CalculationFormula" = '', "Description" = 'Market range: €1.9 - €2.1', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-140';
UPDATE "ServiceSkus" SET "BasePrice" = 3.20, "CalculationFormula" = '', "Description" = 'Market range: €5.95 - €6.55', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-138';
UPDATE "ServiceSkus" SET "BasePrice" = 18.08, "CalculationFormula" = '', "Description" = 'Market range: €33.68 - €37.06', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-043';
UPDATE "ServiceSkus" SET "BasePrice" = 3.58, "CalculationFormula" = '', "Description" = 'Market range: €5 - €9', "UnitType" = '€/кв.м' WHERE "SkuCode" = 'TILE-003';
UPDATE "ServiceSkus" SET "BasePrice" = 5.83, "CalculationFormula" = '', "Description" = 'Market range: €10.85 - €11.95', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-111';
UPDATE "ServiceSkus" SET "BasePrice" = 168.73, "CalculationFormula" = '1', "Description" = 'Душ кабина.', "UnitType" = 'pcs' WHERE "SkuCode" = 'PLMB-SHOWER-CABIN';
UPDATE "ServiceSkus" SET "BasePrice" = 1.45, "CalculationFormula" = '', "Description" = 'Market range: €2.69 - €2.97', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-076';
UPDATE "ServiceSkus" SET "BasePrice" = 4.38, "CalculationFormula" = '', "Description" = 'Market range: €8.16 - €8.98', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-143';
UPDATE "ServiceSkus" SET "BasePrice" = 1.66, "CalculationFormula" = '', "Description" = 'Market range: €3 - €3.5', "UnitType" = '€/лин.м' WHERE "SkuCode" = 'ELEC-020';
UPDATE "ServiceSkus" SET "BasePrice" = 22.30, "CalculationFormula" = '', "Description" = 'Market range: €41.53 - €45.7', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-095';
UPDATE "ServiceSkus" SET "BasePrice" = 23.01, "CalculationFormula" = '', "Description" = 'Market range: €40 - €50', "UnitType" = '€/курс' WHERE "SkuCode" = 'DEMO-003';
UPDATE "ServiceSkus" SET "BasePrice" = 1.53, "CalculationFormula" = '1', "Description" = 'Грундиране на стени и тавани.', "UnitType" = 'sqm' WHERE "SkuCode" = 'PANT-PRIMER';
UPDATE "ServiceSkus" SET "BasePrice" = 48.57, "CalculationFormula" = '1', "Description" = 'Плочи над 60х120 см.', "UnitType" = 'sqm' WHERE "SkuCode" = 'TILE-LARGE';
UPDATE "ServiceSkus" SET "BasePrice" = 7.16, "CalculationFormula" = '1', "Description" = 'Цялостна шпакловка.', "UnitType" = 'sqm' WHERE "SkuCode" = 'PANT-SPACKLE-STD';
UPDATE "ServiceSkus" SET "BasePrice" = 11.66, "CalculationFormula" = '', "Description" = 'Market range: €21.71 - €23.9', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-131';
UPDATE "ServiceSkus" SET "BasePrice" = 34.12, "CalculationFormula" = '', "Description" = 'Market range: €63.56 - €69.93', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-093';
UPDATE "ServiceSkus" SET "BasePrice" = 10.23, "CalculationFormula" = '', "Description" = '20', "UnitType" = 'Per Quantity (Item)' WHERE "SkuCode" = 'ELEC-002';
UPDATE "ServiceSkus" SET "BasePrice" = 46.02, "CalculationFormula" = '1', "Description" = 'Монтаж на мивки.', "UnitType" = 'pcs' WHERE "SkuCode" = 'PLMB-SINK-INSTALL';
UPDATE "ServiceSkus" SET "BasePrice" = 2.05, "CalculationFormula" = '', "Description" = 'Market range: €3.8 - €4.19', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-104';
UPDATE "ServiceSkus" SET "BasePrice" = 40.90, "CalculationFormula" = '', "Description" = 'Къртене на голям отвор в стената за скрит монтаж на апартаментно електрическо табло.', "UnitType" = 'Per Quantity (Item)' WHERE "SkuCode" = 'ELEC-012';
UPDATE "ServiceSkus" SET "BasePrice" = 6.14, "CalculationFormula" = '', "Description" = '', "UnitType" = 'Per sqm' WHERE "SkuCode" = 'TILE-005';
UPDATE "ServiceSkus" SET "BasePrice" = 12.78, "CalculationFormula" = '', "Description" = 'Монтаж и подвързване на трансформатор за скрито LED осветление.', "UnitType" = 'Per Quantity (Item)' WHERE "SkuCode" = 'ELEC-015';
UPDATE "ServiceSkus" SET "BasePrice" = 22.30, "CalculationFormula" = '', "Description" = 'Market range: €41.53 - €45.7', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-091';
UPDATE "ServiceSkus" SET "BasePrice" = 2.17, "CalculationFormula" = '', "Description" = 'Market range: €4.04 - €4.46', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-062';
UPDATE "ServiceSkus" SET "BasePrice" = 2.79, "CalculationFormula" = '', "Description" = 'Market range: €4.9 - €6', "UnitType" = '€/бр' WHERE "SkuCode" = 'ELEC-023';
UPDATE "ServiceSkus" SET "BasePrice" = 26.41, "CalculationFormula" = '', "Description" = 'Market range: €48.3 - €55', "UnitType" = '€/бр' WHERE "SkuCode" = 'ELEC-024';
UPDATE "ServiceSkus" SET "BasePrice" = 28.12, "CalculationFormula" = '1', "Description" = 'Девиаторни ключове.', "UnitType" = 'pcs' WHERE "SkuCode" = 'ELEC-POINT-DEV';
UPDATE "ServiceSkus" SET "BasePrice" = 75.86, "CalculationFormula" = '', "Description" = 'Market range: €141.3 - €155.44', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-056';
UPDATE "ServiceSkus" SET "BasePrice" = 45.23, "CalculationFormula" = '', "Description" = 'Market range: €84.24 - €92.67', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-100';
UPDATE "ServiceSkus" SET "BasePrice" = 9.02, "CalculationFormula" = '', "Description" = 'Market range: €16.3 - €19', "UnitType" = '€/бр' WHERE "SkuCode" = 'ELEC-028';
UPDATE "ServiceSkus" SET "BasePrice" = 2.63, "CalculationFormula" = '', "Description" = 'Market range: €4.9 - €5.4', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-030';
UPDATE "ServiceSkus" SET "BasePrice" = 1.53, "CalculationFormula" = '', "Description" = 'Полагане на гофрирана тръба с кабел по под (преди замазка) или зад окачен таван/гипсокартон. Не изисква къртене.', "UnitType" = 'Per Linear Meter' WHERE "SkuCode" = 'ELEC-005';
UPDATE "ServiceSkus" SET "BasePrice" = 1.45, "CalculationFormula" = '', "Description" = 'Market range: €2.69 - €2.97', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-114';
UPDATE "ServiceSkus" SET "BasePrice" = 4.08, "CalculationFormula" = '', "Description" = 'Market range: €7.6 - €8.37', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-052';
UPDATE "ServiceSkus" SET "BasePrice" = 2.05, "CalculationFormula" = '', "Description" = 'Market range: €3.8 - €4.19', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-083';
UPDATE "ServiceSkus" SET "BasePrice" = 5.11, "CalculationFormula" = '', "Description" = 'Market range: €9.51 - €10.47', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-089';
UPDATE "ServiceSkus" SET "BasePrice" = 7.67, "CalculationFormula" = '12 + Count(elec_heavy_appliances) + elec_ac_count', "Description" = 'Подреждане на предпазители.', "UnitType" = 'module' WHERE "SkuCode" = 'ELEC-PANEL-MOD';
UPDATE "ServiceSkus" SET "BasePrice" = 4.21, "CalculationFormula" = '', "Description" = 'Market range: €7.85 - €8.64', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-033';
UPDATE "ServiceSkus" SET "BasePrice" = 25.95, "CalculationFormula" = '', "Description" = 'Market range: €48.34 - €53.19', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-060';
UPDATE "ServiceSkus" SET "BasePrice" = 2.93, "CalculationFormula" = '', "Description" = 'Market range: €5.46 - €6.01', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-081';
UPDATE "ServiceSkus" SET "BasePrice" = 1.32, "CalculationFormula" = '', "Description" = 'Market range: €2.45 - €2.7', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-082';
UPDATE "ServiceSkus" SET "BasePrice" = 1.62, "CalculationFormula" = '', "Description" = 'Market range: €3 - €3.31', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-071';
UPDATE "ServiceSkus" SET "BasePrice" = 25.56, "CalculationFormula" = '1', "Description" = 'Подготовка, защита и логистика на обекта', "UnitType" = 'flat' WHERE "SkuCode" = 'GEN-001';
UPDATE "ServiceSkus" SET "BasePrice" = 2.58, "CalculationFormula" = '', "Description" = 'Market range: €4.6 - €5.5', "UnitType" = '€/бр' WHERE "SkuCode" = 'ELEC-021';
UPDATE "ServiceSkus" SET "BasePrice" = 18.38, "CalculationFormula" = '', "Description" = 'Market range: €34.23 - €37.66', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-090';
UPDATE "ServiceSkus" SET "BasePrice" = 102.26, "CalculationFormula" = '', "Description" = 'Market range: €180 - €220', "UnitType" = '€/бр' WHERE "SkuCode" = 'PLMB-003';
UPDATE "ServiceSkus" SET "BasePrice" = 6.14, "CalculationFormula" = '', "Description" = 'Допълнителна хидроизолация.', "UnitType" = 'sqm' WHERE "SkuCode" = 'MICO-004';
UPDATE "ServiceSkus" SET "BasePrice" = 0.89, "CalculationFormula" = '', "Description" = 'Market range: €1.65 - €1.83', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-137';
UPDATE "ServiceSkus" SET "BasePrice" = 4.38, "CalculationFormula" = '', "Description" = 'Market range: €4.35 - €4.8', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-109';
UPDATE "ServiceSkus" SET "BasePrice" = 0.82, "CalculationFormula" = '', "Description" = 'Market range: €1.53 - €1.69', "UnitType" = '�/177.10 ����' WHERE "SkuCode" = 'ELEC-047';
UPDATE "ServiceSkus" SET "BasePrice" = 16.11, "CalculationFormula" = '', "Description" = 'Market range: €28 - €35', "UnitType" = '€/кв.м' WHERE "SkuCode" = 'TILE-001';
UPDATE "ServiceSkus" SET "BasePrice" = 18.38, "CalculationFormula" = '', "Description" = 'Market range: €34.23 - €37.66', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-094';
UPDATE "ServiceSkus" SET "BasePrice" = 33.23, "CalculationFormula" = '', "Description" = '', "UnitType" = 'Per sqm' WHERE "SkuCode" = 'MICO-001';
UPDATE "ServiceSkus" SET "BasePrice" = 17.90, "CalculationFormula" = 'if(Contains(elec_outlets_comfort, ''Базово''), (global_room_count * 3) + 4, if(Contains(elec_outlets_comfort, ''Комфорт''), (global_room_count * 5) + 6, if(Contains(elec_outlets_comfort, ''Премиум''), (global_room_count * 8) + 10, 0)))', "Description" = 'Труд за 1 брой контакт/ключ.', "UnitType" = 'pcs' WHERE "SkuCode" = 'ELEC-POINT-STD';
UPDATE "ServiceSkus" SET "BasePrice" = 48.57, "CalculationFormula" = 'if(Contains(elec_panel, ''скрито''), 1, 0)', "Description" = 'Къртене на голям отвор в стената за скрит монтаж на апартаментно електрическо табло.', "UnitType" = 'pcs' WHERE "SkuCode" = 'ELEC-PANEL-NICHE';
UPDATE "ServiceSkus" SET "BasePrice" = 1.45, "CalculationFormula" = '', "Description" = 'Market range: €2.69 - €2.97', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-065';
UPDATE "ServiceSkus" SET "BasePrice" = 0.43, "CalculationFormula" = '', "Description" = 'Market range: €0.79 - €0.88', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-074';
UPDATE "ServiceSkus" SET "BasePrice" = 11.76, "CalculationFormula" = '', "Description" = 'Market range: €18 - €28', "UnitType" = '€/кв.м' WHERE "SkuCode" = 'DRYW-002';
UPDATE "ServiceSkus" SET "BasePrice" = 23.01, "CalculationFormula" = '1', "Description" = 'Монтаж на окачен таван.', "UnitType" = 'sqm' WHERE "SkuCode" = 'DRYW-CEILING-STD';
UPDATE "ServiceSkus" SET "BasePrice" = 2.05, "CalculationFormula" = '', "Description" = 'Market range: €3.8 - €4.19', "UnitType" = '�/��' WHERE "SkuCode" = 'ELEC-077';
UPDATE "ServiceSkus" SET "BasePrice" = 97.15, "CalculationFormula" = '1', "Description" = 'Конзолна тоалетна.', "UnitType" = 'pcs' WHERE "SkuCode" = 'PLMB-WC-BUILTIN';
UPDATE "ServiceSkus" SET "BasePrice" = 6.14, "CalculationFormula" = '', "Description" = 'Изкопаване на канал за полагане на кабели в твърд стоманобетон. Най-трудният и бавен процес.', "UnitType" = 'Per Linear Meter' WHERE "SkuCode" = 'ELEC-003';
