
-- =========================================================================
-- BUILDSMART LIVE DATABASE CLEANUP
-- 1. Strips English tags from Categories and Translations
-- 2. Updates the JSON Question Templates
-- =========================================================================

-- 1. STRIP ENGLISH TAGS
UPDATE "ServiceCategories" SET "Name" = REPLACE("Name", ' (Electrical)', '');
UPDATE "ServiceCategories" SET "Name" = REPLACE("Name", ' (Plumbing)', '');
UPDATE "ServiceCategories" SET "Name" = REPLACE("Name", ' (Painting)', '');
UPDATE "ServiceCategories" SET "Name" = REPLACE("Name", ' (Demolition)', '');
UPDATE "ServiceCategories" SET "Name" = REPLACE("Name", ' (Drywall)', '');
UPDATE "ServiceCategories" SET "Name" = REPLACE("Name", ' (Tiling)', '');
UPDATE "ServiceCategories" SET "Name" = REPLACE("Name", ' (Microcement)', '');

UPDATE "ServiceCategoryTranslations" SET "Name" = REPLACE("Name", ' (Electrical)', '');
UPDATE "ServiceCategoryTranslations" SET "Name" = REPLACE("Name", ' (Plumbing)', '');
UPDATE "ServiceCategoryTranslations" SET "Name" = REPLACE("Name", ' (Painting)', '');
UPDATE "ServiceCategoryTranslations" SET "Name" = REPLACE("Name", ' (Demolition)', '');
UPDATE "ServiceCategoryTranslations" SET "Name" = REPLACE("Name", ' (Drywall)', '');
UPDATE "ServiceCategoryTranslations" SET "Name" = REPLACE("Name", ' (Tiling)', '');
UPDATE "ServiceCategoryTranslations" SET "Name" = REPLACE("Name", ' (Microcement)', '');


-- 2. UPDATE JSON TEMPLATES
UPDATE "ServiceCategories" SET "TemplateStructure" = '{}', "UpdatedAt" = now() WHERE "Name" = 'Electrical';
UPDATE "ServiceCategories" SET "TemplateStructure" = '{"questions": [{"id": "q2f1a2", "text": "fssq", "type": "boolean", "required": false}, {"id": "qd59b8", "text": "cdsad", "type": "choice", "options": ["Option 1", "Option 2", "Option 3"], "required": false}, {"id": "q8d38d", "text": "ghjk", "type": "multiselect", "options": ["Option 1567", "Option 2", "Option 3", "Option 4"], "required": true}]}', "UpdatedAt" = now() WHERE "Name" = 'Cat 3';
UPDATE "ServiceCategories" SET "TemplateStructure" = '{"questions": [{"id": "drywall_type", "text": "Какво ще се изгражда от гипсокартон?", "type": "multiselect", "options": ["Окачен таван", "Преградни стени", "Предстенна обшивка (на конструкция)", "Куфари (обличане на тръби)"], "required": true}, {"id": "drywall_rooms", "text": "В колко помещения ще се прави гипсокартон?", "type": "choice", "options": ["Само в банята (влагоустойчив)", "В 1 стая", "В 2-3 стаи", "В целия обект"], "required": true}, {"id": "drywall_insulation", "text": "Желаете ли поставяне на изолация (вата) зад картона?", "type": "choice", "options": ["Да, стандартна вата", "Да, специална шумоизолация", "Не"], "required": true}]}', "UpdatedAt" = now() WHERE "Name" = 'Сухо строителство';
UPDATE "ServiceCategories" SET "TemplateStructure" = '{"questions": [{"id": "mico_area", "text": "Къде ще се полага микроциментът?", "type": "multiselect", "options": ["Сухи зони (подове и стени в стаи)", "Мокри зони (Баня)"], "required": true}, {"id": "mico_rooms", "text": "В колко помещения?", "type": "choice", "options": ["Само в банята", "В 1-2 стаи", "В целия обект"], "required": true}]}', "UpdatedAt" = now() WHERE "Name" = 'Микроцимент';
UPDATE "ServiceCategories" SET "TemplateStructure" = '{"questions": [{"id": "demo_what", "text": "Какво точно трябва да се кърти?", "type": "multiselect", "options": ["Цяла баня (стари плочки и санитария)", "Вътрешни тухлени стени", "Бетонни/Панелни стени", "Стари подови настилки (замазка/мозайка)"], "required": true}, {"id": "demo_rooms", "text": "В колко помещения ще се извършва къртене?", "type": "choice", "options": ["Само в банята", "В 1-2 стаи", "В целия обект"], "required": true}, {"id": "demo_disposal", "text": "Желаете ли извозване на строителните отпадъци?", "type": "choice", "options": ["Да, искам контейнер и извозване", "Не, ще се справя сам"], "required": true}]}', "UpdatedAt" = now() WHERE "Name" = 'Къртене и извозване';
UPDATE "ServiceCategories" SET "TemplateStructure" = '{"questions": [{"id": "tile_type", "text": "Какъв тип настилки ще се полагат?", "type": "multiselect", "options": ["Стандартни плочки (до 60х60)", "Голямоформатен гранитогрес (над 60х120)", "Ламиниран паркет"], "required": true}, {"id": "tile_rooms", "text": "Къде ще се полагат настилките?", "type": "multiselect", "options": ["Баня / Мокри помещения", "Кухня / Коридор", "Спални / Хол"], "required": true}, {"id": "tile_prep", "text": "Каква подготовка на пода е нужна?", "type": "multiselect", "options": ["Саморазливна замазка (за изравняване)", "Хидроизолация (за бани)", "Не знам (майсторът да прецени)"], "required": true}]}', "UpdatedAt" = now() WHERE "Name" = 'Подови и стенни настилки';
UPDATE "ServiceCategories" SET "TemplateStructure" = '{"questions": [{"id": "paint_tasks", "text": "Какви дейности са необходими?", "type": "multiselect", "options": ["Цялостна шпакловка", "Само боядисване", "Сваляне на тапети"], "required": true}, {"id": "paint_sqm", "text": "Каква е общата площ на стените и таваните (кв.м.)?", "type": "number", "required": true}, {"id": "paint_trim_doors", "text": "Ще се боядисват ли интериорни врати или декоративни первази?", "type": "boolean", "required": true}, {"id": "paint_colors", "text": "Колко различни цвята ще се използват?", "type": "choice", "options": ["Един цвят", "2-3 цвята (акцентни стени)", "Множество цветове"], "required": true}, {"id": "paint_finish_level", "text": "Какво е очакваното ниво на завършеност на стените?", "type": "choice", "options": ["Стандартно (Q3/Q4)", "Перфектно гладко (Q5 - изисква специална шпакловка)"], "required": true}]}', "UpdatedAt" = now() WHERE "Name" = 'Painting';
UPDATE "ServiceCategories" SET "TemplateStructure" = '{"questions": [{"id": "global_property_type", "text": "Какъв е типът на имота?", "type": "choice", "options": ["Апартамент", "Къща / Вила", "Офис / Търговско помещение"], "required": true}, {"id": "global_total_sqm", "text": "Каква е общата квадратура (подова площ) на обекта в кв.м.?", "type": "number", "required": true}, {"id": "global_ceiling_height", "text": "Каква е височината на таваните?", "type": "choice", "options": ["Стандартна (между 2.50м и 2.70м)", "Висока (над 2.70м)"], "required": true}, {"id": "global_room_count", "text": "Общ брой сухи помещения (спални, хол, кухня, кабинет)?", "type": "number", "required": true}, {"id": "global_bathroom_count", "text": "Колко на брой са мокрите помещения (бани и тоалетни)?", "type": "number", "required": true}, {"id": "global_current_state", "text": "Какво е текущото състояние на обекта?", "type": "choice", "options": ["Ново строителство (на шпакловка и замазка / БДС)", "Празно жилище за основен ремонт", "Обзаведено жилище (изисква местене и покриване)"], "required": true}, {"id": "global_logistics", "text": "Има ли осигурен достъп и паркомясто за бус/контейнер, както и работещ асансьор за качване на материали?", "type": "choice", "options": ["Да, има лесен достъп и асансьор", "Няма асансьор (качване по стълби)", "Труден достъп/Няма паркинг"], "required": true}, {"id": "global_materials_supply", "text": "Кой ще осигури видимите материали (плочки, санитария, ламинат, осветителни тела)?", "type": "choice", "options": ["Аз ще ги купя (търся само труд)", "Искам майсторът да ги достави (по каталог)", "Смесено (ще се уговорим допълнително)"], "required": true}, {"id": "global_protection", "text": "Изисква ли се ежедневно почистване и специално покриване/защита на общите части на сградата?", "type": "boolean", "required": true}]}', "UpdatedAt" = now() WHERE "Name" = 'Global Questions';
UPDATE "ServiceCategories" SET "TemplateStructure" = '{"questions": [{"id": "paint_scope", "text": "Какво е текущото състояние на стените и какво желаете да се направи?", "type": "choice", "options": ["Освежаване (Само боядисване върху здрава основа)", "Стандартен ремонт (Шпакловка и боядисване)", "Сваляне на тапети, шпакловка и боядисване"], "hintText": "💡 Ако имате пукнатини или грапавини, изберете ''Стандартен ремонт'', за да се изгладят.", "required": true}, {"id": "paint_rooms", "text": "Кои помещения ще се боядисват?", "type": "multiselect", "options": ["Всички стаи", "Хол / Всекидневна", "Спални", "Коридор / Антре", "Само тавани (в мокри помещения)"], "required": true}, {"id": "paint_colors", "text": "Какви цветове ще използвате?", "type": "choice", "options": ["Всичко в бяло (най-бързо и бюджетно)", "Светли цветове", "Тъмни или наситени цветове", "Смесено (бял таван, цветни стени)"], "required": true}, {"id": "paint_finish_level", "text": "Какво е очакваното ниво на гладкост?", "type": "choice", "options": ["Стандартно (добро за матови и светли бои)", "Перфектно гладко (Q5 - задължително за тъмни бои и силно осветление)"], "hintText": "💡 Q5 изисква специални готови смеси и перфектно машинно шлайфане.", "required": true, "dependsOn": "paint_scope", "dependsOnValue": "Стандартен ремонт (Шпакловка и боядисване)|Сваляне на тапети, шпакловка и боядисване"}, {"id": "paint_trim_doors_count", "text": "Имате ли стари интериорни врати, които искате майсторът да реставрира и пребоядиса?", "type": "choice", "options": ["0", "1", "2", "3", "4+"], "required": true}]}', "UpdatedAt" = now() WHERE "Name" = 'Бояджийски и шпакловъчни услуги';
UPDATE "ServiceCategories" SET "TemplateStructure" = '{"questions": [{"id": "plumb_scope", "text": "Какъв е мащабът на ВиК ремонта?", "type": "choice", "options": ["Цялостна подмяна (нови тръби и канали)", "Само извеждане на нови ВиК изводи (точки)", "Само монтаж (на мивки, душове, тоалетни)"], "hintText": "💡 Ако тръбите ви са стари (метални), препоръчваме цялостна подмяна с полипропилен.", "required": true}, {"id": "plumb_rooms", "text": "В кои помещения ще се извършват ВиК дейности?", "type": "multiselect", "options": ["Баня", "Кухня", "Мокро помещение / Перално", "Втора тоалетна"], "required": true}, {"id": "plumb_wc_type", "text": "Какъв тип тоалетна ще монтираме?", "type": "choice", "options": ["Стандартна (моноблок)", "Вградена структура (конзолна)", "Няма да се монтира тоалетна"], "required": true}, {"id": "plumb_shower_type", "text": "Каква ще бъде душ зоната?", "type": "choice", "options": ["Само душ батерия / окачване", "Душ кабина или стъклен параван", "Вана", "Няма да има душ"], "required": true}, {"id": "plumb_sink_count", "text": "Колко мивки (за баня и кухня) общо ще се монтират?", "type": "choice", "options": ["0", "1", "2", "3+"], "required": true}, {"id": "plumb_appliances", "text": "Какви други уреди ще свързваме към ВиК мрежата?", "type": "multiselect", "options": ["Пералня", "Съдомиялна", "Електрически бойлер (до 100л)"], "required": true}, {"id": "plumb_riser", "text": "Ще подменяме ли главния вертикален щранг (общите тръби)?", "type": "choice", "options": ["Да, искам подмяна", "Не, остават старите", "Не знам (ще се реши на място)"], "required": true}]}', "UpdatedAt" = now() WHERE "Name" = 'ВиК Услуги';
UPDATE "ServiceCategories" SET "TemplateStructure" = '{"questions": [{"id": "elec_walls", "text": "От какво са направени стените ви в момента?", "type": "choice", "options": ["Бетон / Панел", "Тухла", "Гипсокартон", "Смесено"], "required": true}, {"id": "elec_floor_sqm", "text": "Колко кв.м. нова замазка на пода ще правим? (Пускането на кабели по пода преди замазка пести много къртене. 0 ако няма)", "type": "number", "required": true}, {"id": "elec_heavy_appliances", "text": "Колко на брой големи уреди ще имате?", "type": "number", "required": true}, {"id": "elec_ac_count", "text": "Колко броя климатици ще имате общо?", "type": "number", "required": true}, {"id": "elec_underfloor_heating_rooms", "text": "В колко на брой помещения ще имате подово отопление?", "type": "number", "required": true}, {"id": "elec_boiler_count", "text": "Колко бойлера (стандартни или проточни) ще имате? (Захранване)", "type": "number", "required": true}, {"id": "elec_outlets", "text": "Колко общо стандартни контакти и ключове желаете?", "type": "number", "required": true}, {"id": "elec_deviators", "text": "Колко девиаторни ключа искате?", "type": "number", "required": true}, {"id": "elec_lighting", "text": "Какъв тип ще е основното осветление?", "type": "multiselect", "options": ["Полилеи и плафони (стандартно)", "Вградени лунички / LED спотове", "Скрито LED осветление (ленти в окачен таван)", "Аплици (стенно осветление)"], "required": true}, {"id": "elec_lan_tv_count", "text": "За колко на брой стаи искате интернет кабел (LAN/TV)?", "type": "number", "required": true}, {"id": "elec_security_points", "text": "Колко слаботокови точки (камери, СОТ) ще имате?", "type": "number", "required": true}, {"id": "elec_panel", "text": "Главното ел. табло ще бъде скрито или външно?", "type": "choice", "options": ["Скрито/Вградено", "Външно/Открито"], "required": true}, {"id": "elec_blinds_count", "text": "За колко прозореца ще имате ел. щори?", "type": "number", "required": true}, {"id": "elec_fans_count", "text": "Колко вентилатора за баня ще монтираме?", "type": "number", "required": true}, {"id": "elec_three_phase", "text": "Имате ли налична партида за трифазен ток?", "type": "boolean", "required": true}]}', "UpdatedAt" = now() WHERE "Name" = 'Електрическа Инсталация ';
UPDATE "ServiceCategories" SET "TemplateStructure" = '{"questions": [{"id": "elec_scope", "text": "Какъв е мащабът на ремонта?", "type": "choice", "options": ["Цялостна подмяна (всичко се изгражда наново)", "Частичен ремонт (добавяне/местене на контакти и лампи)", "Само монтаж (на ключове, контакти и осветителни тела)"], "hintText": "💡 Ако инсталацията ви е над 20 години, препоръчваме цялостна подмяна.", "required": true}, {"id": "elec_walls", "text": "От какво са направени стените ви в момента?", "type": "choice", "options": ["Бетон / Панел (най-трудно за къртене)", "Тухла", "Гипсокартон / Окачен таван (без къртене)", "Смесено"], "required": true, "dependsOn": "elec_scope", "dependsOnValue": "Цялостна подмяна (всичко се изгражда наново)|Частичен ремонт (добавяне/местене на контакти и лампи)"}, {"id": "elec_heavy_appliances", "text": "Кои мощни уреди ще имате? (Изберете всички)", "type": "multiselect", "options": ["Фурна", "Индукционен котлон", "Съдомиялна", "Пералня", "Сушилня", "Проточен бойлер"], "required": true}, {"id": "elec_ac_count", "text": "Колко климатика ще се захранват?", "type": "choice", "options": ["0", "1", "2", "3", "4+"], "required": true}, {"id": "elec_outlets_comfort", "text": "Колко контакти желаете във всяка стая?", "type": "choice", "options": ["Базово (по 3-4 на стая)", "Комфорт (по 5-6 на стая)", "Премиум (над 8 на стая)"], "hintText": "💡 Повечето ни клиенти избират ''Комфорт'', за да избегнат разклонители.", "required": true}, {"id": "elec_lighting", "text": "Какъв тип ще е основното осветление?", "type": "multiselect", "options": ["Стандартно (полилеи/плафони)", "Вградени лунички", "Скрито LED осветление"], "required": true}, {"id": "elec_panel", "text": "Главното ел. табло ще се подменя ли?", "type": "choice", "options": ["Да, искам ново скрито (вградено) табло", "Да, искам ново външно табло", "Не, остава старото"], "required": true}]}', "UpdatedAt" = now() WHERE "Name" = 'Електрическа Инсталация';
