query GetTradesmanProfiles {
  tradesmanProfiles {
    id
    videoIntroductionUrl
    averageRating
    isVerified
    user {
      id
      firstName
      lastName
      profilePictureUrl
      location
      bio
    }
    skills {
        serviceCategory {
            name
        }
        verificationStatus
    }
    media {
      id
      videoUrl
      thumbnailUrl
      isActive
      createdAt
    }
    milestoneMedia {
      id
      jobId
      url
      type
      createdAt
    }
  }
}