mutation RegisterUser($firstName: String!, $lastName: String!, $email: String!, $password: String!, $phoneNumber: String, $utmSource: String, $utmMedium: String, $utmCampaign: String, $utmContent: String, $utmTerm: String) {
  registerUser(firstName: $firstName, lastName: $lastName, email: $email, password: $password, phoneNumber: $phoneNumber, utmSource: $utmSource, utmMedium: $utmMedium, utmCampaign: $utmCampaign, utmContent: $utmContent, utmTerm: $utmTerm) {
    id
    firstName
    lastName
    email
    phoneNumber
  }
}